### ISSUE TITLE
Fix build warnings (wait until 2023-01-18)

### ISSUE THREAD

**Issue by dave-burke** [skill-collectors/guesstimator#171]
## Summary

Build warnings should be cleaned up.  Wait for Pulumi to update (see #4 below)

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-node, aws-actions/configure-aws-credentials, pulumi/setup-pulumi, pulumi/actions, aws-actions/configure-aws-credentials, actions/setup-node, actions/checkout

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

## Steps

In cd.yml

1. Update `actions/checkout` from v2 to v3
2. Update `actions/setup-node` from v2 to v3
3. Update `aws-actions/configure-aws-credentials` from v1 to v1-node16
4. !! [Can't update `pulumi/*` until 2022-12-07](https://github.com/pulumi/actions/issues/752)

## Tests

All existing tests should pass. No warnings should be printed on the GH Actions Summary page.

## Documentation

NA

**Comment by RobbieMcKinstry** [comment]
GH has delayed the deprecation of GHE v3.3 until 18 Jan 2023. As a result, that's the new "do not merge until" date for this PR. :(

**Comment by dave-burke** [comment]
Thanks for the proactive heads up, and thanks for all your work on Pulumi!
