### ISSUE TITLE
Call /status API endpoint from home page

### ISSUE THREAD

**Issue by dave-burke** [skill-collectors/guesstimator#195]
## Summary

By invoking a trivial endpoint on the lambda, we can minimize wait time for a "cold start" when someone clicks the "create room" button.

## Steps

1. Call `rest.get('/status')` in `frontend/src/routes/+page.svelte` inside an `onMount` function.
2. If the call returns an error, consider a custom message that replaces the "Create a room" button with something like "API is unavailable".

## Tests

NA

## Documentation

NA

**Comment by DA-Mike** [comment]
I'd like to take a shot at this if it's still open.

**Comment by dave-burke** [comment]
Go for it! Let me know if you get stuck. FYI LocalStack is not working since I merged the WebSocket API because apigatewayv2 [is a pro feature](https://docs.localstack.cloud/references/coverage/#apigatewayv2). I will probably just remove localstack at some point, but for now the docs are outdated in that regard.

**Comment by DA-Mike** [comment]
Hey Dave, sorry it's been taking me so long on this, finally had time to sit down and dive into it. It's fair to say most of the tech stack is new to me, so I've spent most of my time navigating that. I'm fairly certain I have the code for the fix, but I can't get the backend up and running so I can test it. The deploy-local.sh gets hung up during creation. Any tips would be appreciated.

**Comment by dave-burke** [comment]
Hey! No problem. `deploy-local.sh` isn't going to work because it calls `pulumilocal up` which tries to initialize the Pulumi stack on localstack, and localstack has been broken since I added the WebSocket API.

If you have a Pulumi account and an AWS account set up and configured together, then you could use `deploy-dev.sh` and it will deploy the app into your Pulumi/AWS acount.

Otherwise, you could just use the public dev instance. To do that, create a file at `frontend/.env.development` and put the following in it:

```js
VITE_PUBLIC_API_URL=https://1rf96svdk1.execute-api.us-east-1.amazonaws.com/stage/
VITE_PUBLIC_API_KEY=nA7QdeOoBjaLuqencdjKDcfCK7iTz7WaG2IVwoYh
VITE_PUBLIC_WEB_SOCKET_URL=wss://ez4uwcuho2.execute-api.us-east-1.amazonaws.com/stage
```

(note that the API key is [not a secret](https://skill-collectors.github.io/guesstimator/context/infra/rate-limits))

Then you can run `npm run dev` in the frontend project and it should work.

**Comment by DA-Mike** [comment]
Hey Dave, could you assign it to me? It doesn't appear that I can do the normal workflow of creating a branch from the issue, not to mention push or create a PR, thanks!

**Comment by DA-Mike** [comment]
Unfortunately it's not letting me push. I created my own local branch originally as this issue page won't allow me to create a branch directly from the issue, so maybe that's the problem. Sorry to keep bothering you about this!
