### ISSUE TITLE
Add a favicon and set page title

### ISSUE THREAD

**Issue by dave-burke** [skill-collectors/guesstimator#196]
## Summary

Currently favicon is the sveltekit default and title is just the url.

## Steps

1. Find or create a favicon and save it as `frontend/static/favicon.png`
2. See [here](https://kit.svelte.dev/docs/seo#manual-setup-title-and-meta) for adding titles to pages. Just one title in `frontend/src/routes/+layout.svelte` would probably be sufficient unless there is a compelling reason to do otherwise. Note that we don't care about SEO at this time.

## Tests

E2E tests?

## Documentation

Possibly include attribution for favicon if required.

**Comment by mjp2233** [comment]
Throwing this out there.... what if the favicon was a question mark made with the Fibonacci Spiral?  

Like these, but maybe thicker lines.
![Image](https://user-images.githubusercontent.com/36688412/203188369-b87ebb39-18eb-4694-ba24-5b4aa83fc29a.png)

**Comment by dave-burke** [comment]
That's a really cool idea! I wonder if it would be easy to make as a vector graphic, since the line is mathematically defined. I have zero experience making vector graphics, though, so who knows.

**Comment by dave-burke** [comment]
@mjp2233  It's [live](https://guesstimator.superfun.link/)! I just erased the measurements (too small to see in an icon) and thickened the lines as you suggested. Turned out great!
