### ISSUE TITLE
Add 'report bug' and 'request feature' to the footer

### ISSUE THREAD

**Issue by dave-burke** [skill-collectors/guesstimator#350]
## Summary

Add links to the footer to submit a bug report or feature request (to create an issue in GitHub)

## Steps

Add the links:
- https://github.com/skill-collectors/guesstimator/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=
- https://github.com/skill-collectors/guesstimator/issues/new?assignees=&labels=bug&template=bug_report.md&title=

Also consider updating each template to instruct submitters to search the [existing issues](https://github.com/skill-collectors/guesstimator/issues) for existing tasks related to their issue.

## Tests

Visual inspection is fine

## Documentation

NA

**Comment by yuvrxj-afk** [comment]
Would like to contribute.
